---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ${SYSTEM_NAME}-${INSTANCE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${BACKEND_IMAGE}
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ${SYSTEM_NAME}-${INSTANCE}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ${SYSTEM_NAME}
    app.kubernetes.io/instance: ${INSTANCE}
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend
  namespace: ${SYSTEM_NAME}-${INSTANCE}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ${SYSTEM_NAME}
    app.kubernetes.io/instance: ${INSTANCE}
spec:
  rules:
    - host: ${SYSTEM_NAME}-${INSTANCE}-backend.${DNS_DOMAIN}
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 80
            path: /
  tls:
    - {}
